### ISSUE TITLE
Error deleting messages

### ISSUE THREAD

**Issue by b-morgan** [thess/callattendant#28]
I was finally able to get a working copy of this project with:
`pip3 install 'callattendant @ git+https://github.com/thess/callattendant'`

While playing around I generated a couple of messages but when I went to delete them, I got the following error:
```
pi@rpi3bplus:~ $ callattendant
Command line options:
  --config=None
  --data-path=None
  --create-folder=False
Initializing Modem
Opening serial port
Looking for modem on /dev/ttyACM0
*** US Robotics modem detected ***
Serial port opened on /dev/ttyACM0
Modem initialized
MSG LED pulsing
Starting the Flask webapp
MSG count: 2
Running the Flask server
Approved LED blinking: 2 times
Waiting for call...
 * Serving Flask app 'callattendant'
 * Debug mode: off
Removing message
[2024-03-03 08:40:29,554] ERROR in app: Exception on /messages/delete/1 [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/pi/.local/lib/python3.9/site-packages/callattendant/userinterface/webapp.py", line 948, in messages_delete
    message = Message(get_db(), current_app.config.get("MASTER_CONFIG"))
TypeError: __init__() missing 1 required positional argument: 'event'

```

**Comment by thess** [comment]
Sorry 'bout that - Reverted an (incomplete) internal optimization 

Fixed in: https://github.com/thess/callattendant/commit/76a1a6fa4c4f873069429d69031a2cef35f8261f

Installing from the tip of the repository is not guaranteed to be fully ready for release. Caveat User. The latest stable release is here: [v1.6.5](https://github.com/thess/callattendant/releases/tag/v1.6.5)

**Comment by b-morgan** [comment]
I managed to update my copy and verify that this issue is fixed and can be closed.
